### ISSUE TITLE
Option/Preference for including the tab titles in tabs

### ISSUE THREAD

**Issue by fenimore** [fenimore/DemocracyDroid#35]
In the most recent release I took out the tab title ("Story", "Broadcast", "Download"). Some users like it (such as @DerrickRocha), so we should put a shared preference for including the tab titles. Or if the experiment fails, maybe just totally reset and bring back the titles by default.

For the next release we'll just wait and see how it feels 🙂

**Comment by DerrickRocha** [comment]
Nice! I downloaded the new build. I like the download button you added.

 I don't think it would hurt to update the app icon. With devices running
marshmallow and beyond, I believe the icons are rounded by default.

I'll try to get to the loading icon tomarrow. Also, instead of jobmanager,
I'm thinking we might be better with rxjava. It seems like it's a lot
better to manage states. https://youtu.be/0IKHxjkgop4.
Let me know what you think.

**Comment by fenimore** [comment]
Sounds cool!

**Comment by fenimore** [comment]
I'm closing this because I kinda like the icons when it comes down to it :man_shrugging:
